export class SearchForm {
    client_renter_name: string = ''
    client_renter_name2: string = ''
    renter_address: string = ''
    renter_address2: string = ''
    renter_address3: string = ''
    renter_address4: string = ''
    cont_no: string = ''
}

export class RentalForm {
    id: number = 0
    store_prefix: string = ''
    is_black_listed: boolean = false
    to_be_paid: string = ''
    to_be_paid2: string = ''
    to_be_paid3: string = ''
    client_renter_name: string = ''
    client_renter_name2: string = ''
    renter_address: string = ''
    renter_address2: string = ''
    renter_address3: string = ''
    renter_address4: string = ''
    cont_no: string = ''
    business_address: string = ''
    business_address2: string = ''
    business_tel: string = ''
    license_number: string = ''
    license_country: string = ''
    license_date: string = ''
    passport_number: string = ''
    passport_country: string = ''
    passport_date: string = ''
    place_of_birth: string = ''
    date_of_birth: string = ''
    additional_driver: string = ''
    license2_number: string = ''
    license2_country: string = ''
    license2_date: string = ''
    to_be_checked_in_at: string = ''
    date_form: string = ''
    time_form: string = ''
    car_model: string = ''
    car_license: string = ''
    car_owner: string = ''
    car_checked_in_at: string = ''
    car_rented_at: string = ''
    date_in: string = ''
    date_out: string = ''
    obs: string=''
    time_in: string = ''
    time_out: string = ''
    form_number: string = ''
    car_group: string = ''
    car_chargd: string = ''
    car_tarrif: string = ''

}